### PR TITLE
Changes for aucore-blockvote-9: Encounter

### PR DESCRIPTION
**Pull request by dt-r**
This PR addresses issues from the AU Core R1 Ballot for Comment aucore-blockvote-9: https://confluence.hl7.org/display/HAFWG/aucore-blockvote-9

- Made the following changes to AU Core Encounter:
  - removed Must Support from Encounter.identifier [FHIR-45212](https://jira.hl7.org/browse/FHIR-45212)
  - removed Must Support from Encounter.type [FHIR-44580](https://jira.hl7.org/browse/FHIR-44580)
  - removed Must Support from Encounter.hospitalization, Encounter.hospitalization.dischargeDisposition [FHIR-45210](https://jira.hl7.org/browse/FHIR-45210)
  - in Encounter.participant.individual replaced RelatedPerson with AU Base RelatedPerson [FHIR-45228](https://jira.hl7.org/browse/FHIR-45228)
- Updated examples to remove elements that are no longer Must Support
- Updated change log

### CODE REVIEW

**Comment by brettesler-ext** [comment]
Added use of AU Base Related Person profile for Observation.performer: AU Core Diagnostic Result Observation, Changed AU Core Pathology Result Observation

**Comment by brettesler-ext** [comment]
Have reviewed @dt-r's changes - can someone review mine?

**Comment by dbojicic** [comment]
> Have reviewed @dt-r's changes - can someone review mine?

I'll do.

**Review by dbojicic — CHANGES_REQUESTED** [review]
Review comments: 
1. Please update Terminology page to remove resources related to elements that are no longer Must Support
2. In [Must Support - Resource References](https://build.fhir.org/ig/hl7au/au-fhir-core/general-requirements.html#must-support---resource-references), replace RelatedPerson with AU Base RelatedPerson.

**Comment by dt-r** [comment]
> Review comments:
> 
> 1. Please update Terminology page to remove resources related to elements that are no longer Must Support
> 2. In [Must Support - Resource References](https://build.fhir.org/ig/hl7au/au-fhir-core/general-requirements.html#must-support---resource-references), replace RelatedPerson with AU Base RelatedPerson.

Fixed both.

**Review by dbojicic — CHANGES_REQUESTED** [review]
Confirmed above fixes. 

Just one minor change - sorry I missed it in the earlier review. 
Now that Encounter.type is not a MS element, we should remove it from the search parameters (patient+type, type) in both the profile page and the CapabilityStatements.

**Comment by dt-r** [comment]
> Confirmed above fixes.
> 
> Just one minor change - sorry I missed it in the earlier review. Now that Encounter.type is not a MS element, we should remove it from the search parameters (patient+type, type) in both the profile page and the CapabilityStatements.

There is a similar item for dischargeDisposition - the preferred way to handle this is via a Technical Correction (i.e. raise a separate JIRA and track it that way.)

**Comment by dbojicic** [comment]
> https://confluence.hl7.org/display/HAFWG/aucore-blockvote-9



> > Confirmed above fixes.
> > Just one minor change - sorry I missed it in the earlier review. Now that Encounter.type is not a MS element, we should remove it from the search parameters (patient+type, type) in both the profile page and the CapabilityStatements.
> 
> There is a similar item for dischargeDisposition - the preferred way to handle this is via a Technical Correction (i.e. raise a separate JIRA and track it that way.)

Raised https://jira.hl7.org/browse/FHIR-45954.

**Comment by dbojicic** [comment]
Review comments: 
1. In 2.1.2.2 AU Core Capability Statements, change "a AU Core Requester actor" and "a AU Core Responder actor" to use the correct article "an".

**Pull request merged**
