### PR TITLE
QA fixes

### PR DESCRIPTION
**Pull request by dbojicic**
Changes: 
- guidance.html - rename 'AUCDI' to match the page title
- Extensions page - add Indigenous Status to the list of supported extensions
- General Requirements page
  - Profile Only Support - change 'represent' to 'represents'
  - Changed "implement" in “using AU Core profiles (Profile Support) AND implement the…” to "implements"
  -  Must Support - Choice of Data Types
     - changed casing of "age" to "Age"
     - AU Core Pathology Result Observation Observation.effective[x], changed to dateTime, Period
-  Comparison page - updated AU Core v7.0.0 links to point to v7.0.0 - STU7 (two instances)
- AU Core Patient: removed Comparison with other national and international IGs section, and added a link to the comparison page
- AU Core Sex Assigned at Birth: fix broken link to Person Recorded Sex or Gender extension 
- Index page:
  - Changed "Data" to "data" in “AU Core defines the Data model and RESTful API.."
  - Removed "the" from the hyperlink in “…(Profile Support) and [the RESTful FHIR API](http://hl7.org/fhir/R4/http.html) interactions…” 
  - Removed unnecessary line breaks
  - "Medicine Information" page description - changed "medications" to "medication"
  - “AU Core is particularly useful in defining: removed "As" from "As the basis..." & capitalised "The"
  -

### CODE REVIEW

**Comment by dt-r** [comment]
Not sure why 24 files have changed if the PR lists the scope of what's being reviewed? Given it lists 6 pages that should change. Is this 2-5 QA PRs in one big PR?

**Comment by dbojicic** [comment]
> @dbojicic Not sure why 24 files have changed if the PR lists the scope of what's being reviewed? PR description lists 6 pages that should change. Is this 2-5 QA PRs in one big PR?

There are now only 7 files left. Tthe changes involving renumbering invariants in AU Core profiles, which resulted in 24 files being changed, will be provided in another PR.

**Review by JayMurdoch — CHANGES_REQUESTED** [review]
This change has not been applied: General Requirements page > Changed "implement" in “using AU Core profiles (Profile Support) AND implement the…” to "implements"

Thanks.

**Comment by dbojicic** [comment]
> This change has not been applied: General Requirements page > Changed "implement" in “using AU Core profiles (Profile Support) AND implement the…” to "implements"
> 
> Thanks.

Done.

**Review by JayMurdoch — APPROVED** [review]
Final change confirmed. Thanks.

**Pull request merged**
